config_version = 14

[accessibility]
ui_scale = 1.3999999999999999

[audio]
enable_sounds = false

[bar.default]
capsule = true
capsule_padding = 7.0
concave_edge_corners = false
end = [ "status", "tray", "notifications", "network", "bluetooth", "volume", "keyboard_layout", "control-center" ]
font_family = "IosevkaTerm Nerd Font Mono"
font_weight = 600
margin_ends = 0
padding = 12
panel_overlap = 0
position = "bottom"
radius = 0
scale = 1.3500000000000001
shadow = false
start = [ "workspaces", "media" ]
thickness = 48
widget_spacing = 10

[brightness]
enable_ddcutil = true
sync_all_monitors = true

[calendar]

[control_center]
hidden_tabs = [ "power" ]

    [control_center.calendar]
    show_week_numbers = true

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

[desktop_widgets]
enabled = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 10

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Moscow"

[lockscreen]
fingerprint = false
monitors = [ "DP-1" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@FALLBACK",
    "lockscreen-login-box@DP-4",
    "lockscreen-login-box@HDMI-A-2"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1720.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 196.0
    box_width = 810.0
    cx = 1720.0
    cy = 1258.0
    output = "DP-4"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "HDMI-A-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "HDMI-A-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
monitors = [ "DP-1" ]

[osd]
monitors = [ "DP-1" ]
position = "bottom_center"

    [osd.kinds]
    media = false
    power_profile = false

[plugin_settings."davemhammer/tailscale"]
notify_on_peer_change = false

[plugins]
enabled = [ "davemhammer/tailscale" ]

[shell]
font_family = "IosevkaTerm Nerd Font Mono"
telemetry_enabled = true
time_format = "{:%-I:%M %p}"

    [shell.panel]
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    save_to_file = false

    [shell.session]
    grid_columns = 2

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "2"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 5.0
        enabled = true
        shortcut = "3"
        variant = "destructive"

[system.monitor]
enabled = false

[theme]
builtin = "Nord"
community_palette = "Seoul256"
mode = "dark"
pure_black_dark = false
shell_mode = "follow"
source = "community"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kitty", "qt" ]
    community_ids = [ "opencode", "zen-browser", "telegram", "micro", "obsidian", "vscode", "fastfetch", "zathura", "bat", "yazi" ]

[wallpaper]
directory = "/home/sokolawesome/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/sokolawesome/Pictures/Wallpapers/girl-smoking-city-view.jpg"

    [wallpaper.last]
    path = "/home/sokolawesome/Pictures/Wallpapers/girl-smoking-city-view.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/sokolawesome/Pictures/Wallpapers/girl-smoking-city-view.jpg"

    [wallpaper.monitors.DP-4]
    path = "/home/sokolawesome/Pictures/Wallpapers/space-galaxy-stars.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/sokolawesome/Pictures/Wallpapers/girl-smoking-city-view.jpg"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/sokolawesome/Pictures/Wallpapers/space-galaxy-stars.jpg"

[widget.clock]
format = "{:%a %d %b %-I:%M %p}"

[widget.media]
art_size = 18
artist_first = true
capsule = true
hide_when_no_media = true
max_length = 300
title_scroll = "always"

[widget.network]
show_label = false

[widget.status]
capsule = true
scale = 0.90000000000000002
show_counts = false
type = "davemhammer/tailscale:status"