hl.on("hyprland.start", function()
    hl.exec_cmd("xsettingsd")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")

    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
end)
