#################################
#       GENERAL WINDOW RULES    #
#################################

# Prevent windows from being automatically maximized
# windowrule = suppressevent maximize, class:.*
# Ignore focus for unnamed or background XWayland windows
# windowrule = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

#################################
#     WORKSPACE ASSIGNMENTS     #
#################################

# Browsers
windowrule = match:class zen, workspace 5 silent
windowrule = match:class chromium, workspace 5 silent

# Messaging apps
windowrule = match:class org.telegram.desktop, workspace 4 silent,

#################################
#         FLOATING TOOLS        #
#################################

windowrule = match:class blueman-manager, float on

windowrule {
    name = pulseaudio-rule
    match:class = org.pulseaudio.pavucontrol
    float = on
    size = monitor_w*0.25 monitor_h*0.75
    move = (monitor_w) 40
}

# windowrulev2 = float, class:^(nm-connection-editor)$
# windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$
# windowrulev2 = center, class:^(org.kde.polkit-kde-authentication-agent-1)$

windowrule {
    name = pip-rule
    match:title = Picture-in-Picture
    float = on
    pin = on
    size = 1024 720
}

windowrule {
    name = file-chooser-rule
    match:class = xdg-desktop-portal-gtk
    float = on
    center = on
    size = monitor_w/2 monitor_h/2
}

windowrule {
    name = steam-rule
    match:initial_class = steam
    workspace = 7
    no_initial_focus = on
}

windowrule {
    name = steam-updater-rule
    match:title = Steam
    match:class =
    workspace = 7
    no_initial_focus = on
}

windowrule {
    name = steam-app-rule
    match:initial_class = steam_app_
    workspace = 8
    immediate = on
}

windowrule {
    name = steam-friends-list-rule
    match:initial_title = Friends List
    float = on
    center = on
    size = 300 monitor_h*0.6
}

windowrule {
    name = steam-settings-rule
    match:initial_title = Steam Settings
    float = on
    center = on
    size = monitor_w/2 monitor_h/2
}

windowrule {
    name = steam-browser-rule
    match:initial_title = Steam - Browser
    float = on
    center = on
    size = monitor_w*0.8 monitor_h*0.8
}
