legacy_layout=0

background_alpha=0.6
round_corners=0
background_color=000000
font_size=24
text_color=C0C0C0
position=top-left
hud_compact
gpu_list=0
table_columns=3
gpu_text=GPU
gpu_stats
vram
vram_color=F1003B
gpu_core_clock
gpu_mem_clock
gpu_temp
gpu_mem_temp
gpu_fan
gpu_power
gpu_color=F1003B
cpu_text=CPU
cpu_stats
cpu_mhz
cpu_temp
cpu_power
cpu_color=FA8000
ram
ram_color=FA8000
fps
frame_timing
frametime_color=FA8000
show_fps_limit
fps_limit_method=late
toggle_fps_limit=Shift_L+F1
fps_limit=165,120,60,0
#offset=0
fsr
hdr
gamemode
vsync=4
output_folder=/home/sokolawesome/.local/share/goverlay
log_duration=30
log_interval=100
toggle_hud=Shift_L+F2
toggle_logging=Shift_R+F2
blacklist=zenity,protonplus,lsfg-vk-ui,bazzar,gnome-calculator,pamac-manager,lact,ghb,bitwig-studio,ptyxis,yumex
