directory: /mnt/hdd/music
library: /mnt/hdd/library.db

import:
    move: yes

plugins: deezer spotify info inline scrub

item_fields:
  primary_albumartist: albumartist.split(',')[0]

paths:
  default: $primary_albumartist/$album/$track $title
