git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never

gui:
  theme:
    activeBorderColor:
      - "#76946a"
      - bold
    inactiveBorderColor:
      - "#c0a36e"
    searchingActiveBorderColor:
      - "#7e9cd8"
      - bold
    optionsTextColor:
      - "#717c7c"
    selectedLineBgColor:
      - "#717c7c"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#717c7c"
    cherryPickedCommitBgColor:
      - "#7e9cd8"
    markedBaseCommitFgColor:
      - "#7e9cd8"
    markedBaseCommitBgColor:
      - "#c34043"
    unstagedChangesColor:
      - "#c34043"
    defaultFgColor:
      - "#c8c093"
